[bumpversion]
current_version = "1.2.0"
commit = true
tag = true
tag_name = "chart-v{new_version}"

[[bumpversion.files]]
filename = "charts/urban-model-platform/Chart.yaml"
search = 'version: {current_version}'
replace = 'version: {new_version}'
