{{- if not .Values.geoserverConnection.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ump.fullname" . }}-geoserver-connection
  labels:
    {{ include "ump.labels" . | nindent 4 }}
data:
  UMP_GEOSERVER_URL: "aHR0cDovL2dlb3NlcnZlcjo4MDgw"
  UMP_GEOSERVER_DB_HOST: ""
  UMP_GEOSERVER_DB_PORT: "NTQzMg=="
  UMP_GEOSERVER_DB_NAME: ""
  UMP_GEOSERVER_DB_USER: ""
  UMP_GEOSERVER_DB_PASSWORD: ""
  UMP_GEOSERVER_WORKSPACE_NAME: ""
  UMP_GEOSERVER_USER: ""
  UMP_GEOSERVER_PASSWORD: ""
  UMP_GEOSERVER_CONNECTION_TIMEOUT: "MTA="
{{- end -}}