{{- if not .Values.keycloakConnection.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ump.fullname" . }}-geoserver-connection
  labels:
    {{ include "ump.labels" . | nindent 4 }}
data:
  GEOSERVER_URL: ""
  GEOSERVER_DB_HOST: ""
  GEOSERVER_DB_PORT: ""
  GEOSERVER_WORKSPACE_NAME: ""
  GEOSERVER_USER: ""
  GEOSERVER_PASSWORD: ""
{{- end -}}